### ISSUE TITLE
Parse Error at PicketBox module.xml 

### ISSUE THREAD

**Issue by emag** [wildfly-swarm/wildfly-swarm#7] opened 2015-05-06 06:41 UTC
WildFly Swarm is indeed what I wanted! Thanks.

BTW, I got a parse error at PicketBox module.xml. It seems `name` attribute(${org.picketbox:picketbox}) of `resources -> artifact` doesn't resolve.  Any idea?

``` sh
$ git clone https://github.com/wildfly-swarm/example-jaxrs.git
$ mvn clean package
$ java -jar target/wildfly-swarm-example-jaxrs-1.0.0.Beta1-SNAPSHOT-swarm.jar
15:33:19,758 INFO  [org.jboss.msc] (main) JBoss MSC version 1.2.4.Final
15:33:19,878 INFO  [org.jboss.as] (MSC service thread 1-6) WFLYSRV0049: WildFly Core 1.0.0.CR1 "Kenny" starting
15:33:19,918 ERROR [org.jboss.msc.service.fail] (MSC service thread 1-6) MSC000001: Failed to start service jboss.as: org.jboss.msc.service.StartException in service jboss.as: Failed to start service
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: org.jboss.modules.ModuleLoadError: Error loading module from modules/system/layers/base/org/picketbox/main/module.xml
	at org.jboss.modules.ModuleLoadException.toError(ModuleLoadException.java:74)
	at org.jboss.modules.Module.getPathsUnchecked(Module.java:1384)
	at org.jboss.modules.Module.loadModuleClass(Module.java:555)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:353)
	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:432)
	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:269)
	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:77)
	at org.jboss.modules.Module.loadModuleClass(Module.java:560)
	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:348)
	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
	at org.jboss.as.server.ApplicationServerService.service(ApplicationServerService.java:224)
	at org.jboss.as.server.ApplicationServerService.start(ApplicationServerService.java:153)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
	... 3 more
Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact '${org.picketbox:picketbox}' (position: END_TAG seen ...<resources>\n        <artifact name="${org.picketbox:picketbox}"/>... @32:54) 
	at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:890)
	at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:729)
	at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:494)
	at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:287)
	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:150)
	at org.jboss.modules.BootModuleFinder.findModule(BootModuleFinder.java:48)
	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
	at org.jboss.modules.Module.addPaths(Module.java:1028)
	at org.jboss.modules.Module.link(Module.java:1398)
	at org.jboss.modules.Module.getPaths(Module.java:1359)
	at org.jboss.modules.Module.getPathsUnchecked(Module.java:1382)
	... 30 more

15:33:19,932 ERROR [stderr] (main) Exception in thread "main" java.lang.reflect.InvocationTargetException
15:33:19,933 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:33:19,933 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:33:19,933 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:33:19,934 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:497)
15:33:19,934 ERROR [stderr] (main) 	at org.wildfly.swarm.bootstrap.Main.main(Main.java:37)
15:33:19,934 ERROR [stderr] (main) Caused by: java.lang.reflect.InvocationTargetException
15:33:19,934 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
15:33:19,935 ERROR [stderr] (main) 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
15:33:19,935 ERROR [stderr] (main) 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
15:33:19,935 ERROR [stderr] (main) 	at java.lang.reflect.Method.invoke(Method.java:497)
15:33:19,935 ERROR [stderr] (main) 	at org.wildfly.swarm.container.Main.main(Main.java:44)
15:33:19,935 ERROR [stderr] (main) 	... 5 more
15:33:19,935 ERROR [stderr] (main) Caused by: java.lang.IllegalStateException: WFLYSRV0141: Cannot start server
15:33:19,936 ERROR [stderr] (main) 	at org.jboss.as.server.BootstrapImpl.startup(BootstrapImpl.java:156)
15:33:19,936 ERROR [stderr] (main) 	at org.jboss.as.server.SelfContainedContainer.start(SelfContainedContainer.java:102)
15:33:19,936 ERROR [stderr] (main) 	at org.wildfly.swarm.container.Container.start(Container.java:79)
15:33:19,936 ERROR [stderr] (main) 	at org.wildfly.swarm.container.DefaultMain.main(DefaultMain.java:9)
15:33:19,936 ERROR [stderr] (main) 	... 10 more
15:33:19,936 ERROR [stderr] (main) Caused by: java.util.concurrent.ExecutionException: Operation failed
15:33:19,936 ERROR [stderr] (main) 	at org.jboss.threads.AsyncFutureTask.operationFailed(AsyncFutureTask.java:74)
15:33:19,937 ERROR [stderr] (main) 	at org.jboss.threads.AsyncFutureTask.get(AsyncFutureTask.java:268)
15:33:19,937 ERROR [stderr] (main) 	at org.jboss.as.server.BootstrapImpl.startup(BootstrapImpl.java:152)
15:33:19,937 ERROR [stderr] (main) 	... 13 more
15:33:19,937 ERROR [stderr] (main) Caused by: org.jboss.msc.service.StartException in service jboss.as: Failed to start service
15:33:19,937 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1904)
15:33:19,937 ERROR [stderr] (main) 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
15:33:19,937 ERROR [stderr] (main) 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
15:33:19,938 ERROR [stderr] (main) 	at java.lang.Thread.run(Thread.java:745)
15:33:19,938 ERROR [stderr] (main) Caused by: org.jboss.modules.ModuleLoadError: Error loading module from modules/system/layers/base/org/picketbox/main/module.xml
15:33:19,938 ERROR [stderr] (main) 	at org.jboss.modules.ModuleLoadException.toError(ModuleLoadException.java:74)
15:33:19,938 ERROR [stderr] (main) 	at org.jboss.modules.Module.getPathsUnchecked(Module.java:1384)
15:33:19,938 ERROR [stderr] (main) 	at org.jboss.modules.Module.loadModuleClass(Module.java:555)
15:33:19,938 ERROR [stderr] (main) 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
15:33:19,938 ERROR [stderr] (main) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
15:33:19,939 ERROR [stderr] (main) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
15:33:19,939 ERROR [stderr] (main) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
15:33:19,939 ERROR [stderr] (main) 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
15:33:19,939 ERROR [stderr] (main) 	at java.lang.ClassLoader.defineClass1(Native Method)
15:33:19,939 ERROR [stderr] (main) 	at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
15:33:19,939 ERROR [stderr] (main) 	at org.jboss.modules.ModuleClassLoader.doDefineOrLoadClass(ModuleClassLoader.java:353)
15:33:19,939 ERROR [stderr] (main) 	at org.jboss.modules.ModuleClassLoader.defineClass(ModuleClassLoader.java:432)
15:33:19,940 ERROR [stderr] (main) 	at org.jboss.modules.ModuleClassLoader.loadClassLocal(ModuleClassLoader.java:269)
15:33:19,940 ERROR [stderr] (main) 	at org.jboss.modules.ModuleClassLoader$1.loadClassLocal(ModuleClassLoader.java:77)
15:33:19,940 ERROR [stderr] (main) 	at org.jboss.modules.Module.loadModuleClass(Module.java:560)
15:33:19,940 ERROR [stderr] (main) 	at org.jboss.modules.ModuleClassLoader.findClass(ModuleClassLoader.java:197)
15:33:19,940 ERROR [stderr] (main) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassUnchecked(ConcurrentClassLoader.java:455)
15:33:19,940 ERROR [stderr] (main) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClassChecked(ConcurrentClassLoader.java:404)
15:33:19,940 ERROR [stderr] (main) 	at org.jboss.modules.ConcurrentClassLoader.performLoadClass(ConcurrentClassLoader.java:385)
15:33:19,941 ERROR [stderr] (main) 	at org.jboss.modules.ConcurrentClassLoader.loadClass(ConcurrentClassLoader.java:130)
15:33:19,941 ERROR [stderr] (main) 	at java.lang.Class.forName0(Native Method)
15:33:19,941 ERROR [stderr] (main) 	at java.lang.Class.forName(Class.java:348)
15:33:19,941 ERROR [stderr] (main) 	at java.util.ServiceLoader$LazyIterator.nextService(ServiceLoader.java:370)
15:33:19,941 ERROR [stderr] (main) 	at java.util.ServiceLoader$LazyIterator.next(ServiceLoader.java:404)
15:33:19,941 ERROR [stderr] (main) 	at java.util.ServiceLoader$1.next(ServiceLoader.java:480)
15:33:19,941 ERROR [stderr] (main) 	at org.jboss.as.server.ApplicationServerService.service(ApplicationServerService.java:224)
15:33:19,942 ERROR [stderr] (main) 	at org.jboss.as.server.ApplicationServerService.start(ApplicationServerService.java:153)
15:33:19,942 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.startService(ServiceControllerImpl.java:1948)
15:33:19,942 ERROR [stderr] (main) 	at org.jboss.msc.service.ServiceControllerImpl$StartTask.run(ServiceControllerImpl.java:1881)
15:33:19,942 ERROR [stderr] (main) 	... 3 more
15:33:19,942 ERROR [stderr] (main) Caused by: org.jboss.modules.xml.XmlPullParserException: Failed to resolve artifact '${org.picketbox:picketbox}' (position: END_TAG seen ...<resources>\n        <artifact name="${org.picketbox:picketbox}"/>... @32:54) 
15:33:19,942 ERROR [stderr] (main) 	at org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:890)
15:33:19,942 ERROR [stderr] (main) 	at org.jboss.modules.ModuleXmlParser.parseResources(ModuleXmlParser.java:729)
15:33:19,943 ERROR [stderr] (main) 	at org.jboss.modules.ModuleXmlParser.parseModuleContents(ModuleXmlParser.java:494)
15:33:19,943 ERROR [stderr] (main) 	at org.jboss.modules.ModuleXmlParser.parseDocument(ModuleXmlParser.java:287)
15:33:19,943 ERROR [stderr] (main) 	at org.jboss.modules.ModuleXmlParser.parseModuleXml(ModuleXmlParser.java:150)
15:33:19,943 ERROR [stderr] (main) 	at org.jboss.modules.BootModuleFinder.findModule(BootModuleFinder.java:48)
15:33:19,943 ERROR [stderr] (main) 	at org.jboss.modules.ModuleLoader.findModule(ModuleLoader.java:452)
15:33:19,943 ERROR [stderr] (main) 	at org.jboss.modules.ModuleLoader.loadModuleLocal(ModuleLoader.java:355)
15:33:19,943 ERROR [stderr] (main) 	at org.jboss.modules.ModuleLoader.preloadModule(ModuleLoader.java:302)
15:33:19,944 ERROR [stderr] (main) 	at org.jboss.modules.Module.addPaths(Module.java:1028)
15:33:19,944 ERROR [stderr] (main) 	at org.jboss.modules.Module.link(Module.java:1398)
15:33:19,944 ERROR [stderr] (main) 	at org.jboss.modules.Module.getPaths(Module.java:1359)
15:33:19,944 ERROR [stderr] (main) 	at org.jboss.modules.Module.getPathsUnchecked(Module.java:1382)
15:33:19,945 ERROR [stderr] (main) 	... 30 more
```

**Comment by kenfinnigan** [comment] 2015-05-06 10:33
Unfortunately I wasn't able to reproduce the above problem by following the steps you described.

Were there any changes made that weren't mentioned above?

Trying to figure out why it has a problem

Thanks

**Comment by smiklosovic** [comment] 2015-05-06 10:42
@kenfinnigan we are using both

**Comment by smiklosovic** [comment] 2015-05-06 10:47
java 1.7 does the same thing

**Comment by smiklosovic** [comment] 2015-05-06 12:34
so our investigation is that it does not work on Fedora 21 nor 18. It does work on CentOS 6 and it does work, surprisingly, on FreeBSD 10.1. I think that @kenfinnigan is using something different from Fedora hence I think that Fedoras are distributions to blame however it is super weird really.

**Comment by kenfinnigan** [comment] 2015-05-06 12:45
I'm on Ubuntu and I think @bobmcwhirter is on Mac.

But yes, very weird for it to be specific to Fedora

**Comment by ctomc** [comment] 2015-05-06 13:19
it might be related to maven's settings.xml you guys have. jboss-modules tries to load it and use its repositories to download stuff.

**Comment by bobmcwhirter** [comment] 2015-05-06 13:20
We actually subvert that portion of JBoss Modules if I recall, replacing it with our own maven GAV resolver.

**Comment by kenfinnigan** [comment] 2015-05-06 13:23
That's correct, we don't use the Maven resolver within JBoss Modules, so it doesn't actually read the settings.xml

**Comment by emag** [comment] 2015-05-06 13:25
OS OK/NG Summary.

## OK

* CentOS 6.6
* FreeBSD 10.1
* Mac OS X(10.10.2)

## NG

* Fedora 18, 21
* Ubuntu 14.0.4

**Comment by kenfinnigan** [comment] 2015-05-06 13:28
Interesting, Ubuntu 15.04 works fine for me

**Comment by smiklosovic** [comment] 2015-05-06 13:30
@emag add ubuntu to 15.04 to the list please

**Comment by ctomc** [comment] 2015-05-06 13:30
according to stacktrace it is exactly there :)
anyhow, i would recommend setting logging for org.jboss.modules to TRACE or at least
org.jboss.modules.MavenArtifactUtil to TRACE, this will let us know if it is trying to use jboss-module's maven resolver

**Comment by bobmcwhirter** [comment] 2015-05-06 13:33
Yah, we replace ModuleXmlParser, so

org.jboss.modules.ModuleXmlParser.parseArtifact(ModuleXmlParser.java:890)

is actually our code that calls out to our resolver (separate class).

You can install the LoggingSubsystem into your Container (if you provide a main()) and set logging to whatever you like.  I think.

**Comment by jamezp** [comment] 2015-05-06 14:35
The issue is the version isn't specified in the maven coordinates. There's an attempt to resolve it, but it finds the incorrect version on some OS's. I'm looking into fixing it now.

**Comment by emag** [comment] 2015-05-06 15:46
I checked ModuleXmlParser.

When `repoPath` is `m2repo/org/picketbox/picketbox`, `entryName` is `m2repo/org/picketbox/picketbox-commons/1.0.0.final/picketbox-commons-1.0.0.final.jar` matches, so  `version` is assigned `1.0.0.final`.

`repoPath` should check end character?

https://github.com/wildfly-swarm/wildfly-swarm/blob/1.0.0.Alpha1/bootstrap/src/main/java/org/jboss/modules/ModuleXmlParser.java#L785

**Comment by jamezp** [comment] 2015-05-06 19:42
Should be fixed with the following https://github.com/wildfly-swarm/wildfly-swarm/pull/12

**Comment by emag** [comment] 2015-05-06 19:54
@jamezp  Wow! your PR is great and I checked it works on Fedora 21.
@bobmcwhirter Please ignore my PR.

**Closed** 2015-05-06 20:02 UTC
